### PR TITLE
Install dependencies with Node.

### PR DESCRIPTION
**Pull request by ahmadawais**
Install dependencies with Node.
```sh
npm install -D redux react-router react-redux redux-thunk react-router-dom
```

### CODE REVIEW

**Comment by chrisjpatty** [comment]
This is a good fix for now if Yarn isn't available. In a future release it should detect the presence of yarn and fallback to npm. Thanks for contributing!

**Comment by ahmadawais** [comment]
Sure thing.
BTW @chrisjpatty  I checked the node modules and the following pacakges didn't install. Nor were they found in the package.json file of the app created after I ran and created the app. Can you check if that's true on your end as well?

```
redux react-router react-redux redux-thunk react-router-dom
```

**Comment by ahmadawais** [comment]
Sure thing.
BTW @chrisjpatty  I checked the node modules and the following packages didn't install. Nor were they found in the package.json file of the app created after I ran and created the app. Can you check if that's true on your end as well?

```
redux react-router react-redux redux-thunk react-router-dom
```

**Comment by ahmadawais** [comment]
Fixes #1

**Comment by chrisjpatty** [comment]
@ahmadawais What OS & terminal are you running? I'll check on my side here.

**Comment by chrisjpatty** [comment]
@ahmadawais I think I've identified the problem. The script appears to fail when trying to `cd` into the directory created by `create-react-app`. It should probably switch into that directory using an absolute path from the root instead of a relative path from the current directory. It's installing the packages, just in the parent directory instead.

**Comment by ahmadawais** [comment]
@chrisjpatty Seems that way. Do you have a fix?

**Comment by chrisjpatty** [comment]
@ahmadawais I think so, I just pushed a fix that's working on my end at least.

**Pull request merged**
